spring:
  rabbitmq:
    password: 14135276mq
    port: 5672
    host: localhost
    username: haooon
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
    config:
      discovery:
        serviceId: config-server
        enabled: true
      profile: dev
      label: master
    consul:
      port: 8500
      discovery:
        healthCheckUrl: http://${server.ip}:${server.port}/actuator/health
        healthCheckInterval: 15s
        instance-id: spring-cloud-config-client
  application:
    name: config-client
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,health,info
server:
  ip: 172.20.35.102
  port: 8881