spring:
  rabbitmq:
    password: guest
    port: 5672
    host: localhost
    username: guest
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
    config:
      discovery:
        serviceId: config-server
        enabled: true
      profile: dev
      label: master
  application:
    name: config-client
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8881
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/