spring:
  cloud:
    config:
      server:
        git:
          searchPaths: respo
          uri: https://github.com/haooon/SpringcloudConfig
          username: your username
          password: your password
      label: master
    consul:
      port: 8500
      discovery:
        healthCheckUrl: http://${server.ip}:${server.port}/actuator/health
        healthCheckInterval: 15s
        instance-id: spring-cloud-config-sever
  application:
    name: config-server
server:
  ip: 172.20.35.102
  port: 8888